spring:
  datasource:
    url: jdbc:h2:file:./data/satellitedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  port: 8080

grpc:
  client:
    telemetry-service:
      address: static://localhost:9091
      negotiation-type: plaintext
