# space-operation-center/src/main/resources/application.yml
spring:
  application:
    name: space-operation-center
  datasource:
    url: jdbc:postgresql://localhost:5432/satellite_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none   # выключаем автоматическую генерацию DDL
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: public
  sql:
    init:
      mode: always          # выполнять schema.sql при запуске
      schema-locations: classpath:schema.sql
  cache:
    type: redis
    cache-names:
      - satellite
      - constellation
      - satellites
    redis:
      time-to-live: 600000   # дефолтный TTL (если не переопределён в коде)
  redis:
    host: localhost
    port: 6379
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 2

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,caches
  endpoint:
    metrics:
      enabled: true
    caches:
      enabled: true

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
