spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/telemetry
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: telemetry-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: satelliteEvent:com.example.telemetry.dto.SatelliteEvent
      auto-offset-reset: earliest
      enable-auto-commit: false   # ручное управление offset

server:
  port: 8081
