spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: telemetry-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: satelliteEvent:com.example.telemetry.dto.SatelliteEvent
    listener:
      missing-topics-fatal: false

grpc:
  server:
    port: 9091

logging:
  level:
    com.example.telemetry: INFO
